mm-page_alloc-skip-over-regions-of-invalid-pfns-on-uma-fix
if IS_ENABLED doesn't work same as ifdef around an expression and
so we need an existing stub for the called function if we want to use
it. Compiler complains otherwise

../mm/page_alloc.c: In function 'memmap_init_zone':
../mm/page_alloc.c:5450:5: error: implicit declaration of function 'memblock_next_valid_pfn' [-Werror=implicit-function-declaration]
     pfn = memblock_next_valid_pfn(pfn, end_pfn) - 1;
     ^

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Michal Hocko <mhocko@suse.com>