Revert "Kbuild: always define endianess in kconfig.h"
This reverts commit 524b246fc4f80b06dd01c65326164453b0c0ec90.

Build fails on microblace and others with:

lib/find_bit.c:176:15: error: redefinition of 'find_next_zero_bit_le'
 unsigned long find_next_zero_bit_le(const void *addr, unsigned
               ^
In file included from ./include/asm-generic/bitops.h:35:0,
                 from ./arch/microblaze/include/generated/asm/bitops.h:1,
                 from ./include/linux/bitops.h:38,
                 from lib/find_bit.c:19:
./include/asm-generic/bitops/le.h:12:29: note: previous definition of 'find_next_zero_bit_le' was here
 static inline unsigned long find_next_zero_bit_le(const void *addr,

This is not a problem in linux-next but as this is not directly related
to MM patches I simply revert this change.

Signed-off-by: Michal Hocko <mhocko@suse.com>